include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    always_put_required_named_parameters_first: false
    always_use_package_imports: false
    library_private_types_in_public_api: false
    sort_pub_dependencies: false
    no_leading_underscores_for_local_identifiers: true
    unnecessary_to_list_in_spreads: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    depend_on_referenced_packages: false
    use_truncating_division: true
    omit_obvious_local_variable_types: true
    specify_nonobvious_local_variable_types: true
    omit_local_variable_types: false