include: package:yet_another_lint/defaults.yaml

formatter:
  page_width: 80
analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
