import 'package:flutter/material.dart';

import 'font_family.dart';

/// Material 3 has one type scale containing two sets of type styles:
/// 15 baseline and 15 emphasized. Both of these style sets follow the same
/// scale from Display Large to Label Small.
///
/// The emphasized styles were added in the expressive update. They have a higher weight and other minor adjustments compared to the baseline styles, and are best applied to bold, selection, and other areas of emphasis. Baseline and emphasized styles are meant to be used together.
///
/// ![](https://lh3.googleusercontent.com/amY56CFDJ81aqWy-r-zpQAOH7D0J7NcLDAwmuuikQnZjnYA4NWUs_V2C8LbxFeekKK7u4itaTFKgnRcXm-QFA56Uoe0N4Jvw38RM5tb5Pas)
///
/// The scale is a range of contrasting styles that support the needs of
/// various product contexts and content. No single product will use all
/// the styles. Instead, select styles from the scale that are most appropriate.
///
/// Where emphasized styles can be used
///
/// See also:
///
/// * [M3 guidelines: typography, overview](https://m3.material.io/styles/typography/overview)
/// * [M3 guidelines: typography, type scale & tokens](https://m3.material.io/styles/typography/type-scale-tokens)
/// * [M3 guidelines: typography, where emphasized styles can be used](https://m3.material.io/styles/typography/type-scale-tokens#c898d7e2-4833-440c-9dba-9a95c8f50ac9)
abstract final class M3TypeScale {
  /// Creates a baseline Material 3 typography with [baselineTokens].
  ///
  /// See also:
  ///
  /// * [Typography.material2021], which is a base for this typography style.
  /// * [Baseline type style tokens](https://m3.material.io/styles/typography/type-scale-tokens#84c60429-0cca-4792-b3d2-2305e22429ba)
  static Typography baseline({
    TargetPlatform platform = TargetPlatform.android,
    ColorScheme colorScheme = const ColorScheme.light(),
    String? fontFamily,
    String? displayFontFamily,
  }) {
    TextTheme tokens = baselineTokens;

    if (fontFamily != null || displayFontFamily != null) {
      tokens = TypographyFontFamilyUtils.applyFontFamily(
        textTheme: tokens,
        fontFamily: fontFamily,
        displayFontFamily: displayFontFamily,
      );
    }

    return Typography.material2021(
      platform: platform,
      colorScheme: colorScheme,
      black: tokens,
      white: tokens,
      englishLike: tokens,
      dense: tokens,
      tall: tokens,
    );
  }

  /// Creates an emphasized Material 3 typography with [emphasizedTokens].
  ///
  /// See also:
  ///
  /// * [Typography.material2021], which is a base for this typography style.
  /// * [Emphasized type style tokens](https://m3.material.io/styles/typography/type-scale-tokens#a56472a3-f826-48f2-b32a-c07704f2fb89)
  static Typography emphasized({
    TargetPlatform platform = TargetPlatform.android,
    ColorScheme colorScheme = const ColorScheme.light(),
    String? fontFamily,
    String? displayFontFamily,
  }) {
    TextTheme tokens = emphasizedTokens;

    if (fontFamily != null || displayFontFamily != null) {
      tokens = TypographyFontFamilyUtils.applyFontFamily(
        textTheme: tokens,
        fontFamily: fontFamily,
        displayFontFamily: displayFontFamily,
      );
    }

    return Typography.material2021(
      platform: platform,
      colorScheme: colorScheme,
      black: tokens,
      white: tokens,
      englishLike: tokens,
      dense: tokens,
      tall: tokens,
    );
  }

  /// Defines text geometry for [ScriptCategory.englishLike] scripts, such as
  /// English, French, etc.
  ///
  /// See also:
  ///
  /// * [Baseline type style tokens](https://m3.material.io/styles/typography/type-scale-tokens#84c60429-0cca-4792-b3d2-2305e22429ba)
  static const baselineTokens = TextTheme(
    displayLarge: TextStyle(
      debugLabel: 'md.sys.typescale.display-large',
      inherit: false,
      fontWeight: FontWeight.w400,
      fontSize: 57,
      letterSpacing: -0.25,
      height: 64 / 57,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(400),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(57),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    displayMedium: TextStyle(
      debugLabel: 'md.sys.typescale.display-medium',
      inherit: false,
      fontWeight: FontWeight.w400,
      fontSize: 45,
      letterSpacing: 0,
      height: 52 / 45,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(400),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(45),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    displaySmall: TextStyle(
      debugLabel: 'md.sys.typescale.display-small',
      inherit: false,
      fontWeight: FontWeight.w400,
      fontSize: 36,
      letterSpacing: 0,
      height: 44 / 36,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(400),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(36),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    headlineLarge: TextStyle(
      debugLabel: 'md.sys.typescale.headline-large',
      inherit: false,
      fontWeight: FontWeight.w400,
      fontSize: 32,
      letterSpacing: 0,
      height: 40 / 32,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(400),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(32),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    headlineMedium: TextStyle(
      debugLabel: 'md.sys.typescale.headline-medium',
      inherit: false,
      fontWeight: FontWeight.w400,
      fontSize: 28,
      letterSpacing: 0,
      height: 36 / 28,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(400),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(28),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    headlineSmall: TextStyle(
      debugLabel: 'md.sys.typescale.headline-small',
      inherit: false,
      fontWeight: FontWeight.w400,
      fontSize: 24,
      letterSpacing: 0,
      height: 32 / 24,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(400),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(24),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    titleLarge: TextStyle(
      debugLabel: 'md.sys.typescale.title-large',
      inherit: false,
      fontWeight: FontWeight.w400,
      fontSize: 22,
      letterSpacing: 0,
      height: 28 / 22,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(400),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(22),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    titleMedium: TextStyle(
      debugLabel: 'md.sys.typescale.title-medium',
      inherit: false,
      fontWeight: FontWeight.w500,
      fontSize: 16,
      letterSpacing: 0,
      height: 24 / 16,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(500),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(16),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    titleSmall: TextStyle(
      debugLabel: 'md.sys.typescale.title-small',
      inherit: false,
      fontWeight: FontWeight.w500,
      fontSize: 14,
      letterSpacing: 0.1,
      height: 20 / 14,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(500),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(14),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    bodyLarge: TextStyle(
      debugLabel: 'md.sys.typescale.body-large',
      inherit: false,
      fontWeight: FontWeight.w400,
      fontSize: 16,
      letterSpacing: 0.5,
      height: 24 / 16,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(400),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(16),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    bodyMedium: TextStyle(
      debugLabel: 'md.sys.typescale.body-medium',
      inherit: false,
      fontWeight: FontWeight.w400,
      fontSize: 14,
      letterSpacing: 0.25,
      height: 20 / 14,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(400),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(14),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    bodySmall: TextStyle(
      debugLabel: 'md.sys.typescale.body-small',
      inherit: false,
      fontWeight: FontWeight.w400,
      fontSize: 12,
      letterSpacing: 0.4,
      height: 16 / 12,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(400),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(12),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    labelLarge: TextStyle(
      debugLabel: 'md.sys.typescale.label-large',
      inherit: false,
      fontWeight: FontWeight.w500,
      fontSize: 14,
      letterSpacing: 0.1,
      height: 20 / 14,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(500),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(14),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    labelMedium: TextStyle(
      debugLabel: 'md.sys.typescale.label-medium',
      inherit: false,
      fontWeight: FontWeight.w500,
      fontSize: 12,
      letterSpacing: 0.5,
      height: 16 / 12,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(500),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(12),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    labelSmall: TextStyle(
      debugLabel: 'md.sys.typescale.label-small',
      inherit: false,
      fontWeight: FontWeight.w500,
      fontSize: 11,
      letterSpacing: 0.5,
      height: 16 / 11,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(500),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(11),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
  );

  /// Defines text geometry for [ScriptCategory.englishLike] scripts, such as
  /// English, French, etc.
  ///
  /// See also:
  ///
  /// * [Emphasized type style tokens](https://m3.material.io/styles/typography/type-scale-tokens#a56472a3-f826-48f2-b32a-c07704f2fb89)
  static const emphasizedTokens = TextTheme(
    displayLarge: TextStyle(
      debugLabel: 'md.sys.typescale.emphasized.display-large',
      inherit: false,
      fontWeight: FontWeight.w500,
      fontSize: 57,
      letterSpacing: -0.25,
      height: 64 / 57,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(500),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(57),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    displayMedium: TextStyle(
      debugLabel: 'md.sys.typescale.emphasized.display-medium',
      inherit: false,
      fontWeight: FontWeight.w500,
      fontSize: 45,
      letterSpacing: 0,
      height: 52 / 45,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(500),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(45),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    displaySmall: TextStyle(
      debugLabel: 'md.sys.typescale.emphasized.display-small',
      inherit: false,
      fontWeight: FontWeight.w500,
      fontSize: 36,
      letterSpacing: 0,
      height: 44 / 36,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(500),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(36),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    headlineLarge: TextStyle(
      debugLabel: 'md.sys.typescale.emphasized.headline-large',
      inherit: false,
      fontWeight: FontWeight.w500,
      fontSize: 32,
      letterSpacing: 0,
      height: 40 / 32,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(500),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(32),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    headlineMedium: TextStyle(
      debugLabel: 'md.sys.typescale.emphasized.headline-medium',
      inherit: false,
      fontWeight: FontWeight.w500,
      fontSize: 28,
      letterSpacing: 0,
      height: 36 / 28,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(500),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(28),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    headlineSmall: TextStyle(
      debugLabel: 'md.sys.typescale.emphasized.headline-small',
      inherit: false,
      fontWeight: FontWeight.w500,
      fontSize: 24,
      letterSpacing: 0,
      height: 32 / 24,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(500),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(24),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    titleLarge: TextStyle(
      debugLabel: 'md.sys.typescale.emphasized.title-large',
      inherit: false,
      fontWeight: FontWeight.w500,
      fontSize: 22,
      letterSpacing: 0,
      height: 28 / 22,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(500),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(22),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    titleMedium: TextStyle(
      debugLabel: 'md.sys.typescale.emphasized.title-medium',
      inherit: false,
      fontWeight: FontWeight.w700,
      fontSize: 16,
      letterSpacing: 0,
      height: 24 / 16,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(700),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(16),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    titleSmall: TextStyle(
      debugLabel: 'md.sys.typescale.emphasized.title-small',
      inherit: false,
      fontWeight: FontWeight.w700,
      fontSize: 14,
      letterSpacing: 0.1,
      height: 20 / 14,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(700),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(14),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    bodyLarge: TextStyle(
      debugLabel: 'md.sys.typescale.emphasized.body-large',
      inherit: false,
      fontWeight: FontWeight.w500,
      fontSize: 16,
      letterSpacing: 0.5,
      height: 24 / 16,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(500),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(16),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    bodyMedium: TextStyle(
      debugLabel: 'md.sys.typescale.emphasized.body-medium',
      inherit: false,
      fontWeight: FontWeight.w500,
      fontSize: 14,
      letterSpacing: 0.25,
      height: 20 / 14,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(500),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(14),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    bodySmall: TextStyle(
      debugLabel: 'md.sys.typescale.emphasized.body-small',
      inherit: false,
      fontWeight: FontWeight.w500,
      fontSize: 12,
      letterSpacing: 0.4,
      height: 16 / 12,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(500),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(12),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    labelLarge: TextStyle(
      debugLabel: 'md.sys.typescale.emphasized.label-large',
      inherit: false,
      fontWeight: FontWeight.w700,
      fontSize: 14,
      letterSpacing: 0.1,
      height: 20 / 14,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(700),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(14),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    labelMedium: TextStyle(
      debugLabel: 'md.sys.typescale.emphasized.label-medium',
      inherit: false,
      fontWeight: FontWeight.w700,
      fontSize: 12,
      letterSpacing: 0.5,
      height: 16 / 12,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(700),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(12),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
    labelSmall: TextStyle(
      debugLabel: 'md.sys.typescale.emphasized.label-small',
      inherit: false,
      fontWeight: FontWeight.w700,
      fontSize: 11,
      letterSpacing: 0.5,
      height: 16 / 11,
      textBaseline: TextBaseline.alphabetic,
      leadingDistribution: TextLeadingDistribution.even,
      fontVariations: [
        FontVariation.weight(700),
        FontVariation('GRAD', 0),
        FontVariation.width(100),
        FontVariation('ROND', 0),
        FontVariation.opticalSize(11),
        FontVariation('CRSV', 0),
        FontVariation.slant(0),
        FontVariation('FILL', 0),
        FontVariation('HEXP', 0),
      ],
    ),
  );
}
